#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<-EOSQL
	CREATE USER $MY_USER WITH PASSWORD '$MY_PASSWORD';
	CREATE DATABASE $MY_USER;
	GRANT ALL PRIVILEGES ON DATABASE $MY_USER TO $MY_USER;
	CREATE DATABASE $MY_DB;
	GRANT ALL PRIVILEGES ON DATABASE $MY_DB TO $MY_USER;
EOSQL

